---

- name: This playbook retrieves the size of db's on a host and writes the output to a file.
  hosts: all-databases:&{{ subset | default('NONE')}}
  gather_facts: False
  serial: "0%"
  vars:
    # Determine the engine type
    db_engine: "{%if ((aws_rds is defined and aws_rds.db.engine == 'postgres') or (aws_rds_cluster is defined and aws_rds_cluster.engine == 'aurora-postgresql'))%}postgres{% elif ((aws_rds is defined and aws_rds.db.engine == 'mysql') or (aws_rds_cluster is defined and (aws_rds_cluster.engine == 'aurora-mysql' or aws_rds_cluster.engine == 'aurora')))%}mysql{% else %}unknown{% endif %}"
    # Determine the endpoint based on if the target host is an Instance or Cluster
    endpoint: "{% if jump_host is defined %}{{ inventory_hostname }}{% if aws_rds is defined %}{{ endpoint_postfix }}{% else %}{{aurora_endpoint_postfix}}{% endif %}{% else %}''{% endif %}"

  tasks:
  - name: Retrieve the current date for the output file name
    set_fact: currentdate="{{lookup('pipe','date +%Y%m%d')}}"
    when: db_engine=='aurora-postgresql'

  - name: Configure the output file name
    set_fact: output_file="{{ results_dir }}/database-size-{{ subset }}-{{ currentdate }}.txt"
    when: db_engine=='aurora-postgresql'

  - name: Get database size data
  # psql -h host -d database -U user -W
    shell: "psql -sN -U {{ psql.system_users.monitor_user }} -W'{{ psql.system_users.monitor_passwd }}' -h {{ endpoint }} -e \"SELECT pg_database.datname as "database_name", pg_database_size(pg_database.datname)/1024/1024 AS size_in_mb FROM pg_database ORDER by size_in_mb DESC'\""
    no_log: true
    delegate_to: "{{ jump_host | default( ansible_host ) }}"
    register: r_databasesize
    when: db_engine=='aurora-postgresql'

  - name: Write the resultant database sizes data to output file
    lineinfile:
     line: "{{ inventory_hostname }} \t {{r_databasesize.stdout}}"
     insertafter: EOF
     create: yes
     state: present
     dest: "{{output_file}}"
    delegate_to: 127.0.0.1
    when: db_engine=='aurora-postgresql'
